（	PU
、	PU
）	PU
，	PU
。	PU
“	PU
”	PU
—	PU
；	PU
《	PU
》	PU
——	PU
－－	PU
：	PU
‘	PU
’	PU
－	PU
？	PU
━	PU
──	PU
〈	PU
〉	PU
━━	PU
『	PU
』	PU
———	PU
！	PU
…	PU
·	PU
—－	PU
「	PU
」	PU
∶	PU
＊	PU
／	PU
-	PU
＂	PU
．	PU
＜	PU
＞	PU
`	PU
＇	PU
.	PU
,	PU
?	PU
!	PU
@	PU
#	PU
$	PU
%	PU
^	PU
&	PU
*	PU
(	PU
)	PU
{	PU
[	PU
]	PU
}	PU
|	PU
\	PU
"	PU
'	PU
:	PU
;	PU
<	PU
>	PU
+	PU
=	PU
-	PU
_	PU
一	NUM
二	NUM
三	NUM
四	NUM
五	NUM
六	NUM
七	NUM
八	NUM
九	NUM
十	NUM
百	NUM
千	NUM
万	NUM
日	YMD
月	YMD
年	YMD

